=== drewby08/cse5234/cse5234/EbookStoreSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ROOT">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="USER" minOccurs="0" maxOccurs="unbounded">

					<xs:complexType>
						<xs:sequence>
							<xs:element name="UserID" type="xs:string"></xs:element>
							<xs:element name="CartID" type="xs:string"></xs:element>
							<xs:element name="ReviewID" type="xs:string"></xs:element>
							<xs:element name="ProfileID" type="xs:string"></xs:element>
							<xs:element name="Password" type="xs:string"></xs:element>
							<xs:element name="Admin" type="xs:boolean"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="EBOOK" minOccurs="0" maxOccurs="unbounded">

					<xs:complexType>
						<xs:sequence>
							<xs:element name="ISBN" type="xs:string"></xs:element>
							<xs:element name="Title" type="xs:string"></xs:element>
							<xs:element name="Author" type="xs:string"></xs:element>
							<xs:element name="Price" type="xs:int"></xs:element>
						</xs:sequence>

					</xs:complexType>
				</xs:element>

				<xs:element name="CART" minOccurs="0" maxOccurs="unbounded">

					<xs:complexType>
						<xs:sequence>
							<xs:element name="CartID" type="xs:string"></xs:element>
							<xs:element name="ISBN" type="xs:string"></xs:element>
							<xs:element name="DownloadLink" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="Review" minOccurs="0" maxOccurs="unbounded">

					<xs:complexType>
						<xs:sequence>
							<xs:element name="ReviewID" type="xs:string"></xs:element>
							<xs:element name="ISBN" type="xs:string"></xs:element>
							<xs:element name="UserID" type="xs:string"></xs:element>
							<xs:element name="Stars" type="xs:int"></xs:element>
							<xs:element name="Description" type="xs:string"></xs:element>
						</xs:sequence>

					</xs:complexType>
				</xs:element>

				<xs:element name="Profile" minOccurs="0" maxOccurs="unbounded">

					<xs:complexType>
						<xs:sequence>
							<xs:element name="ProfileID" type="xs:string"></xs:element>
							<xs:element name="FirstName" type="xs:string"></xs:element>
							<xs:element name="LastName" type="xs:string"></xs:element>
							<xs:element name="Address" type="xs:string"></xs:element>
							<xs:element name="Email" type="xs:string"></xs:element>
							<xs:element name="CreditCard" type="xs:string"></xs:element>
						</xs:sequence>

					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== drewby08/cse5234/cse5234/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EbookStoreSchema.xsd">
  <USER>
    <UserID>UserID</UserID>
    <CartID>CartID</CartID>
    <ReviewID>ReviewID</ReviewID>
    <ProfileID>ProfileID</ProfileID>
    <Admin>true</Admin>
  </USER>
  <EBOOK>
    <ISBN>ISBN</ISBN>
    <Title>Title</Title>
    <Author>Author</Author>
    <Price>0</Price>
  </EBOOK>
  <CART>
    <CartID>CartID</CartID>
    <ISBN>ISBN</ISBN>
    <DownloadLink>DownloadLink</DownloadLink>
  </CART>
  <Review>
    <ReviewID>ReviewID</ReviewID>
    <ISBN>ISBN</ISBN>
    <UserID>UserID</UserID>
    <Stars>0</Stars>
    <Description>Description</Description>
  </Review>
  <Profile>
    <ProfileID>ProfileID</ProfileID>
    <FirstName>FirstName</FirstName>
    <LastName>LastName</LastName>
    <Address>Address</Address>
    <Email>Email</Email>
    <CreditCard>CreditCard</CreditCard>
    <Password>Password</Password>
  </Profile>
</ROOT>
